name: "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
    defaults:
      run:
        working-directory: PictureFixer

    steps:
    - uses: actions/checkout@v2
     
    # workaround to force using preview 5 currently due to https://github.com/dotnet/sdk/issues/17865
    # remove this and use setup-dotnet@v1.8.0 when Preview 5 is public
    - name: Setup .NET Preview SDK
      run: |
        wget https://dot.net/v1/dotnet-install.sh
        bash ./dotnet-install.sh -Version 6.0.100-preview.5.21302.13 -Verbose
        echo "$HOME/.dotnet" >> $GITHUB_PATH

    #- name: Setup .NET Core SDK
    #  uses: actions/setup-dotnet@v1.8.0
    #  with:
    #    dotnet-version: 6.0.x #6.0.100-preview.5.21302.13
    #    include-prerelease: true

    - name: Acquire Blazor AOT workload
      run: |
        dotnet workload install microsoft-net-sdk-blazorwebassembly-aot

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build Server/PictureFixer.Server.csproj -c Release

    - name: Publish AOT
      run: dotnet publish Server/PictureFixer.Server.csproj -c Release -o published

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: aot-published
        path: PictureFixer/published